name: IPO監視BOT - 毎朝8時実行

on:
  schedule:
    # 毎日朝8時（JST）に実行（UTC 23:00）
    - cron: '0 23 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  check-ipo:
    runs-on: ubuntu-latest
    
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4
      
    - name: Python 3.12をセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: 依存関係をインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: IPOチェックを実行
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        TZ: Asia/Tokyo
      run: python github_actions_ipo_check.py
